# Generated by Django 5.0.3 on 2024-03-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('classificacao', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('matricula', models.CharField(max_length=20)),
                ('data_de_nasc', models.DateField()),
                ('foto', models.ImageField(upload_to='aluno_fotos/')),
                ('situacao', models.CharField(max_length=50)),
                ('forma_de_ingresso', models.CharField(max_length=50)),
                ('curso_classificacao', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('raca', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.curso')),
            ],
        ),
    ]
