# Generated by Django 5.0.3 on 2024-03-18 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(help_text='Preencher com a cidade do campus universitário.', max_length=50, verbose_name='Nome do Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Curso')),
                ('classificacao', models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo')], max_length=12)),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('EAD', 'Ensino a Distância')], max_length=10)),
                ('periodo', models.CharField(choices=[('Matutino', 'Matutino'), ('Noturno', 'Noturno'), ('Integral', 'Integral')], max_length=8, verbose_name='Período')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(help_text='Informe com pontos e traços.', max_length=14)),
                ('matricula', models.CharField(max_length=9, verbose_name='Matrícula')),
                ('dataDeNasc', models.DateField(help_text='DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(upload_to='home/img/')),
                ('situacao', models.CharField(max_length=10)),
                ('formaDeIngresso', models.CharField(choices=[('ENEM', 'Exame Nacional do Ensino Médio'), ('PSC', 'Processo Seletivo Complementar'), ('Vestibular', 'Vestibular')], max_length=10, verbose_name='Forma de Ingresso')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('raca', models.CharField(choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indigina', 'Indigena'), ('Parda', 'Parda'), ('Preta', 'Preta')], max_length=10, verbose_name='Raça')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.curso')),
            ],
        ),
    ]
