# Generated by Django 5.0.3 on 2024-03-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
    ]
