# Generated by Django 5.0.3 on 2024-03-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aluno_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
    ]
