# Generated by Django 5.0.3 on 2024-03-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aluno_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso_classificacao',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
